name: simple
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  path: ^1.6.0
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
